# Generated by Django 4.2.11 on 2024-04-17 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(default=0, editable=False, help_text='Number of Bells in Change')),
            ],
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('history', models.TextField(blank=True)),
                ('pattern', models.CharField(blank=True, max_length=100, unique=True)),
                ('order', models.SmallIntegerField(default=100, help_text='Ordering of patterns rounds should explicitly be 0')),
                ('number', models.SmallIntegerField(default=0, editable=False, help_text='Bells in Pattern (calculated)')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Tower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ChangeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.SmallIntegerField()),
                ('pattern_str', models.CharField(blank=True, default='', max_length=100)),
                ('change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bells.change')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bells.pattern')),
            ],
        ),
        migrations.AddField(
            model_name='change',
            name='from_pat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_pattern', to='bells.pattern'),
        ),
        migrations.AddField(
            model_name='change',
            name='to_pat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_pattern', to='bells.pattern'),
        ),
        migrations.CreateModel(
            name='Bell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bell', models.CharField(blank=True, max_length=4)),
                ('weight', models.CharField(blank=True, help_text='Bell Weight', max_length=10)),
                ('nominal', models.CharField(blank=True, max_length=10)),
                ('note', models.CharField(blank=True, help_text='Pitch of bell', max_length=3)),
                ('diameter', models.DecimalField(blank=True, decimal_places=3, max_digits=6)),
                ('dated', models.CharField(blank=True, max_length=6)),
                ('founder', models.CharField(blank=True, max_length=100)),
                ('tower', models.ForeignKey(help_text='Tower bell is located in', on_delete=django.db.models.deletion.CASCADE, to='bells.tower')),
            ],
        ),
    ]
