# Generated by Django 4.2.11 on 2024-05-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bells', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='function Name', max_length=60, unique=True)),
                ('order', models.PositiveSmallIntegerField(unique=True)),
                ('active', models.BooleanField(default=True)),
                ('function', models.CharField(max_length=255)),
            ],
        ),
    ]
