# Generated by Django 4.2.11 on 2024-07-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bells', '0002_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='count',
            field=models.SmallIntegerField(help_text='Number of changes in pattern', null=True),
        ),
    ]
