# Generated by Django 4.2.11 on 2024-07-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bells', '0003_pattern_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='enable',
            field=models.BooleanField(default=True, help_text='Enable this Pattern'),
        ),
    ]
